### ISSUE TITLE
API has some brittle points

### ISSUE THREAD

**Issue by epage** [rustic-games/conventional-commit#11]
Noticed these while contributing.  Addressing these would be helpful in moving to a 1.0.
- [x] Module hierarchy: Currently sub-modules are exposed despite everything being top-level. This feels like implementation details are being exposed
  - Suggestion: Expose everything but the typed components only in the top-level.  typed components would be under `conventional::typed`.
- [x] Construction of components is only available via `From` and not `new`
  - Suggestion: Either remove the `From` implementation or add a `new`, depending on if you want people to be able to construct it
- [x] TrailerSeparator's `From` can panic
  - Suggestion: Have a `new`/`parse`, use `TryFrom`, use `ParseString`, or use a non-public API
- [x] Trailer's `From` can panic due to `TrailerSeparator
  - Suggestion: Have a `new`/`parse`, use `TryFrom`, or use `ParseString`, or use a non-public API
- [x] `TrailerSeparator` cannot be extended without breaking changes
  - Suggestion: follow the `__NonExhaustive` (with hidden docs) enum variant convention
- ~~`TrailerSeparator` will require a breaking change if the separator is allowed to be arbitrary, like git due to `Copy` trait.~~  I'm assuming this is unimportant due to the reliance on parsers knowing a hard-coded separator.
- [x] Adding new `ErrorKind`s would be a breaking change
  - Suggestion: like above, follow the convention for non-exhaustive enums
- [x] `BreakingChange` struct seems to be unused

**Comment by JeanMertz** [comment]
Thank you for taking the time to write this up @epage 👍.

I'm in the middle of a job search as I'm wrapping up work at my current employer while also looking for a new employer, so I'm a bit less active at the moment.

Scanning through your suggestions, most of them make sense to me and I would accept PRs making most of the relevant changes. I'll also start picking these off one by one, but that'll probably have to wait until the end of the year.

> Module hierarchy

This is something I'm still struggling with to some extend in Rust, as you can't diverge the internal hierarchy from the public one.

I agree to some extend that it exposes details that you don't necessarily want to expose, but it's a trade-off between structuring your code internally versus having more control over what exactly is exposed in the public API.

Note that nothing is exposed publicly that shouldn't be exposed (to my knowledge), it's just that what _is_ exposed is exposed both at the top-level (for API convenience), and in a submodule (for code structure reasons).

In terms of usage, there's not much difference though, this line is enough to get started:

```rust
use conventional::Commit;
```

But, I'm willing to experiment with this pre-1.0, so if you have some concrete ideas, I'm all ears. It's unclear to me what your current proposal would change in terms of module layout.

> Construction of components is only available via `From` and not `new`

There's no relevant reason why I haven't done this yet, I'm fine adding `new`. I think it makes sense to allow creation of components in the typed API.

> TrailerSeparator's `From` can panic

That's sloppy. I must have copy/pasted that from a previously-internal implementation. Using `FromStr` probably makes most sense in this case?

> `TrailerSeparator` cannot be extended without breaking changes

I agree, it's good to keep our options open in case the spec changes, and a non-exhaustive enum seems like the most sensible choice.

> Adding new `ErrorKinds` would be a breaking change

Agree on non-exhaustive enum.

> `BreakingChange` struct seems to be unused

You are correct. This is dead code left over from the change made in bf552e5a003c8e296a86551b9dfd8612fdd55fdf.

**Comment by epage** [comment]
> I'm in the middle of a job search as I'm wrapping up work at my current employer while also looking for a new employer, so I'm a bit less active at the moment.

Good luck!

**Comment by epage** [comment]
Looks like this is done!  I don't think we should jump straight to 1.0 though.  I'd like to try out the API once this is published to see if anything else comes up.  I'll open those as separate issues.
