### ISSUE TITLE
Parser doesn't support `!` in the subject

### ISSUE THREAD

**Issue by epage** [rustic-games/conventional-commit#4]

**Comment by epage** [comment]
Note that the usage of `!` might change, see https://github.com/conventional-commits/conventionalcommits.org/pull/175

**Comment by JeanMertz** [comment]
This is fixed in ce8ec83df3b3a430d70e923962e2c065b4e62ed7. There'll be some more iterations on this (see the commit message for more details), but at least it's supported now.
