### ISSUE TITLE
Reduce memory allocations

### ISSUE THREAD

**Issue by epage** [rustic-games/conventional-commit#6]
The parser keeps everything in a `String` which requires allocating for each field.  [commited](https://github.com/crate-ci/committed/blob/master/src/conventional.rs#L4) took the approach of using `&str`.

**Comment by epage** [comment]
The problem is that a generalized crate might not be aware of the users needs for allocations.

One way of resolving this is to use `Cow` for everything.

However, I doubt this is going to be enough of an issue in the performance of different applications to be a problem and this issue can probably be rejected.
(created this mostly since it crossed my mind, so I thought my reasoning should be recorded)

**Comment by JeanMertz** [comment]
This one is tackled in 0cae6b329ad1e5dffd7c57a853d6b9f686ca724b.
